/**
 * 2-step Verification Password Container
 */

import React, { Component } from 'react';
import {
    StyleSheet,
    View,
    Text,
    Image,
    TextInput,
    TouchableOpacity
} from 'react-native';
import {
    Container,
    Header,
    HeaderTitle,
    Content,
    Button,
    Icon,
    Loader,
    Toast
} from '@components';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { ActionCreators } from '@actions';
import * as Validation from '@lib/validation';

class Verify2FA extends Component<{}> {

    static navigationOptions = {
        header: null,
    }

    constructor(props) {
        super(props);
        this.state = {};
    }

    componentWillReceiveProps(nextProps){
        if(nextProps && nextProps.errorMsg){
            Toast.errorTop(nextProps.errorMsg);
            this.props.resetMessages();
        }
    }

    render() {
        return (
            <Container>
                <View style={{
                    flex: 1,
                    width: '100%',
                    paddingHorizontal: 40,
                    alignItems: 'center',
                    justifyContent: 'center',
                }}>
                    <View style={{
                        width: '100%',
                        alignItems: 'center',
                        marginBottom: 50,
                        marginTop: 30,
                    }}>
                        <Image style={{
                            alignSelf: 'center',
                            width: '80%',
                            resizeMode: 'contain',
                        }}  source={require('@images/g-auth-icon.png')}/>
                        <Text style={{
                            fontSize: 24,
                            fontWeight: '500',
                            textAlign: 'center',
                            marginVertical: 20,
                        }}>2-STEP VERIFICATION</Text>
                        <Text style={{
                            fontSize: 15,
                            textAlign: 'center',
                            paddingHorizontal: 10,
                        }}>
                            Enter the verification code generated by your mobile application.
                        </Text>
                        <View style={{
                            justifyContent: 'center',
                            marginTop: 20,
                            width: '100%',
                            paddingHorizontal: 15,
                            height: 50,
                            borderWidth: 1.5,
                            borderRadius: 25,
                            borderColor: '#ddd'
                        }}>
                            <TextInput
                                style={{
                                    fontSize: 16,
                                    fontWeight: '600'
                                }}
                                underlineColorAndroid='transparent'
                                placeholder={'Enter verification code'}
                                keyboardType={'numeric'}
                                onChangeText={(verification_code) => this.setState({verification_code})}
                                value={this.state.verification_code || ''}
                            />
                        </View>
                        <Button style={{
                                marginTop: 30,
                                width: '100%',
                                height: 50,
                                justifyContent: 'center',
                                alignItems: 'center',
                                borderRadius: 25,
                            }}
                            textstyle={{
                                fontSize: 20,
                                fontWeight: '600'
                            }}
                            value={'Verify'}
                            onPress={()=>{
                                if(!this.state.verification_code || this.state.verification_code.length < 6){
                                    return Toast.errorTop('Invalid varification code!');
                                }
                                this.props.check2FA(this.state.verification_code);
                            }}
                        />
                        <Button style={{
                                marginTop: 30,
                                width: '100%',
                                height: 50,
                                backgroundColor: '#DFDFDF',
                                justifyContent: 'center',
                                alignItems: 'center',
                                borderRadius: 25,
                            }}
                            textstyle={{
                                fontSize: 20,
                                color: '#333',
                                fontWeight: '600'
                            }}
                            value={'Cancel'}
                            onPress={()=>this.props.logout()}
                        />
                    </View>
                </View>
                <Loader show={this.props.loading} />
            </Container>
        );
    }
}

const styles = StyleSheet.create({

});

function mapStateToProps(state) {
    return {
        loading: state.params.loading,
        isLoggedIn: state.params.isLoggedIn,
        errorMsg: state.params.errorMsg || null,
        successMsg: state.params.successMsg || null
    };
}

function mapDispatchToProps(dispatch) {
    return bindActionCreators(ActionCreators, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(Verify2FA);
