
//action
export const LOGOUT = 'LOGOUT';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

//Transactions
export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const GET_RECENT_TRANSACTIONS = 'GET_RECENT_TRANSACTIONS';
export const GET_SENT_TRANSACTIONS = 'GET_SENT_TRANSACTIONS';
export const GET_RECEIVED_TRANSACTIONS = 'GET_RECEIVED_TRANSACTIONS';
export const RESET_TRANSACTIONS = 'RESET_TRANSACTIONS';
export const UPDATE_TRANSACTION_REPORT_DATE = 'UPDATE_TRANSACTION_REPORT_DATE';

//Home
export const GET_BALANCE = 'GET_BALANCE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_MY_WALLETS = 'GET_MY_WALLETS';

// Navigation
export const NAVIGATE_DASHBOARD = 'NAVIGATE_DASHBOARD';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';
