
//action
export const INIT = 'INIT';
export const CUSTOM_ACTION = 'CUSTOM_ACTION';
export const LOGOUT = 'LOGOUT';

export const LOADING = 'LOADING';
export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const RESET_MESSAGES = 'RESET_MESSAGES';
export const SET_PUBLIC_IP = 'SET_PUBLIC_IP';
export const SET_LOCATION = 'SET_LOCATION';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_NIGHT_MODE = 'CHANGE_NIGHT_MODE';

//Pin
export const CREATE_PIN = 'CREATE_PIN';
export const UPDATE_PIN = 'UPDATE_PIN';
export const ENETER_PIN = 'ENETER_PIN';
export const ENABLE_DISABLE_TOUCH_ID = 'ENABLE_DISABLE_TOUCH_ID';

//2FA
export const START_2FA = 'START_2FA';
export const RESET_2FA = 'RESET_2FA';
export const CONFIRM_2FA_SUCCESS = 'CONFIRM_2FA_SUCCESS';
export const CONFIRM_2FA_FAILED = 'CONFIRM_2FA_FAILED';
export const VERIFY_2FA = 'VERIFY_2FA';
export const VERIFY_2FA_SUCCESS = 'VERIFY_2FA_SUCCESS';
export const VERIFY_2FA_FAILED = 'VERIFY_2FA_FAILED';
export const TURN_OFF_2FA_SUCCESS = 'TURN_OFF_2FA_SUCCESS';
export const TURN_OFF_2FA_FAILED = 'TURN_OFF_2FA_FAILED';
export const MIGRATE_ACCOUNT = 'MIGRATE_ACCOUNT';
export const MIGRATE_ACCOUNT_FAILED = 'MIGRATE_ACCOUNT_FAILED';
export const MIGRATE_ACCOUNT_SUCCESS = 'MIGRATE_ACCOUNT_SUCCESS';

//Wallet
export const STORE_FOUNTAIN_SECRET = 'STORE_FOUNTAIN_SECRET';

//Transactions
export const GET_TRANSACTION_DETAIL = 'GET_TRANSACTION_DETAIL';
export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const GET_RECENT_TRANSACTIONS = 'GET_RECENT_TRANSACTIONS';
export const GET_SENT_TRANSACTIONS = 'GET_SENT_TRANSACTIONS';
export const GET_RECEIVED_TRANSACTIONS = 'GET_RECEIVED_TRANSACTIONS';
export const GET_SHARING_TRANSACTION_DETAIL = 'GET_SHARING_TRANSACTION_DETAIL';
export const GET_SHARING_IN_TRANSACTIONS = 'GET_SHARING_IN_TRANSACTIONS';
export const GET_SHARING_OUT_TRANSACTIONS = 'GET_SHARING_OUT_TRANSACTIONS';
export const GET_SHARING_USAGE_TRANSACTIONS = 'GET_SHARING_USAGE_TRANSACTIONS';

export const RESET_TRANSACTIONS = 'RESET_TRANSACTIONS';
export const UPDATE_TRANSACTION_REPORT_DATE = 'UPDATE_TRANSACTION_REPORT_DATE';
export const SET_BC_MEDIAN_TX_SIZE = 'SET_BC_MEDIAN_TX_SIZE';
export const SET_SATOSHI_PER_BYTE = 'SET_SATOSHI_PER_BYTE';
export const SET_THRESHOLD_AMOUNT = 'SET_THRESHOLD_AMOUNT';
export const SET_FIXED_TXN_FEE = 'SET_FIXED_TXN_FEE';
export const SET_ETHER_GAS_VALUES = 'SET_ETHER_GAS_VALUES';

// Money Request
export const ADD_MONEY_REQUEST = 'ADD_MONEY_REQUEST';
export const GET_INCOMING_REQUESTS = 'GET_INCOMING_REQUESTS';
export const GET_OUTGOING_REQUESTS = 'GET_OUTGOING_REQUESTS';
export const RESET_REQUESTS = 'RESET_REQUESTS';
export const UPDATE_REQUEST_REPORT_DATE = 'UPDATE_REQUEST_REPORT_DATE';

export const ROSTER_OPERATION = 'ROSTER_OPERATION';
export const ADD_ROASTER = 'ADD_ROASTER';
export const MARK_CANCELLED_MONEY_REQUESTS = 'MARK_CANCELLED_MONEY_REQUESTS';
export const MARK_REJECTED_MONEY_REQUESTS = 'MARK_REJECTED_MONEY_REQUESTS';
export const MARK_SENT_MONEY_REQUESTS = 'MARK_SENT_MONEY_REQUESTS';

//Home
export const GET_BALANCE = 'GET_BALANCE';
export const GET_COIN_MARKET_CAP_VALUE = 'GET_COIN_MARKET_CAP_VALUE';
export const GET_MY_WALLETS = 'GET_MY_WALLETS';
export const GET_WALLET_ADDRESS = 'GET_WALLET_ADDRESS';
export const SHOW_QR = 'SHOW_QR';
export const HIDE_QR = 'HIDE_QR';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SEND_VERIFICATION_SMS = 'SEND_VERIFICATION_SMS';
export const VERIFY_PHONE = 'VERIFY_PHONE';
export const SET_RECOVERY_KEYS = 'SET_RECOVERY_KEYS';

// Navigation
export const NAVIGATE_DASHBOARD = 'NAVIGATE_DASHBOARD';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';


// Send/Request Payment
export const SEARCH_WALLET = 'SEARCH_WALLET';
export const RAW_TRANSACTION = 'RAW_TRANSACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const TRANSACTION_BY_ID = 'TRANSACTION_BY_ID';

//Messages
export const GET_MESSAGES = 'GET_MESSAGES';

//Sharing
export const GET_PAYOUT_INFO = 'GET_PAYOUT_INFO';
export const GET_PAYOUT_CODE = 'GET_PAYOUT_CODE';
export const ADD_PAYOUT_CODE = 'ADD_PAYOUT_CODE';
export const REMOVE_PAYOUT_CODE = 'REMOVE_PAYOUT_CODE';

export const GET_SHARING_CODE = 'GET_SHARING_CODE';
export const ADD_SHARING_CODE = 'ADD_SHARING_CODE';
export const UPDATE_SHARING_CODE = 'UPDATE_SHARING_CODE';

//Exchanges
export const GET_FIAT_CURRENCY_EXCHANGE_RATES = 'GET_FIAT_CURRENCY_EXCHANGE_RATES';


//Wagering
export const WAGERING_INIT = 'WAGERING_INIT';
export const GET_ORACLE_EVENTS = 'GET_ORACLE_EVENTS';
export const GET_ORACLE_EVENT = 'GET_ORACLE_EVENT';
export const GET_MY_ACTIVE_ORACLE_EVENTS = 'GET_MY_ACTIVE_ORACLE_EVENTS';
export const GET_MY_ORACLE_EVENTS = 'GET_MY_ORACLE_EVENTS';

export const ADD_ORACLE_WAGER = 'ADD_ORACLE_WAGER';

export const VIEW_ORACLE_EVENT = 'VIEW_ORACLE_EVENT';
export const CREATE_ORACLE_EVENT = 'CREATE_ORACLE_EVENT';
export const UPDATE_ORACLE_EVENT = 'UPDATE_ORACLE_EVENT';
export const DECLARE_ORACLE_EVENT_RESULT = 'DECLARE_ORACLE_EVENT_RESULT';

export const GET_ORACLE_PROFILE = 'GET_ORACLE_PROFILE';
export const SETUP_ORACLE_PROFILE = 'SETUP_ORACLE_PROFILE';
export const UPDATE_ORACLE_PROFILE = 'UPDATE_ORACLE_PROFILE';
export const ENABLE_ORACLE_PROFILE = 'ENABLE_ORACLE_PROFILE';
export const DISABLE_ORACLE_PROFILE = 'DISABLE_ORACLE_PROFILE';
